tests(torrentmanager): fix flaky prefetch_metadata timeout
The test was passing in CI most of the time but occasionally failing:

FAILED deluge/tests/test_torrentmanager.py::TestTorrentmanager::test_prefetch_metadata_timeout -
	AssertionError: assert ('ab570cdd5a1...uhtoncW3rN1l') == ('ab570cdd5a1...1bce173', b'')

This shows there was a race between lt resolving a real magnet from DHT
and the clock timeout.

The test was also not properly patching the reactor clock so was waiting 30
real seconds. And the test needs to advance the clock after the coroutine has
started so that the timeout is registered before the advance rather than
after.